### ISSUE TITLE
(Heisen)bug with tags dictionary

### ISSUE THREAD

**Issue by Natureshadow** [Natureshadow/OSMAlchemy#4]
We have a hard to trace Heisenbug when running the test suite with Python 3. It sometimes fails to retrieve the tags dictionary back from the ORM, the ORM seems to return empty strings on the values side of the dictionaries then:

```
======================================================================
FAIL: test_create_way_with_nodes_and_tags_and_tags_on_node (tests.model.OSMAlchemyModelTestsSQLite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nik/Privat/OSMAlchemy/tests/model.py", line 210, in test_create_way_with_nodes_and_tags_and_tags_on_node
    self.assertEqual(way.tags[u"name"], u"Testway")
AssertionError: '' != 'Testway'
+ Testway
```

It produces a lot of this, but only sometimes. It does *not* appear with Python 2.

It might, however, be, that this is not even a bug in OSMAlchemy or SQLAlchemy, but in the Python 3 testing framework, because the MySQLd and Postgres also die for inobvious reasons on shutdown:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/lib/python3/dist-packages/sqlalchemy/pool.py", line 774, in _reset
    self._reset_agent.rollback()
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1563, in rollback
    self._do_rollback()
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1601, in _do_rollback
    self.connection._rollback_impl()
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 670, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 668, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 420, in do_rollback
    dbapi_connection.rollback()
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) terminating connection due to administrator command
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

**Comment by Natureshadow** [comment]
Turns out it is an issue with PYTHONHASHSEED, and it is an SQLAlchemy bug. Keeping open until there is a work-around for us…
